name: postman-collection
on:
  push:
    branches:
      - main
  workflow_dispatch:        

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        with: 
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref_name != 'develop' && 'develop-merged' ||  github.ref_name }}

      - name: Add logs
        run: |          
          echo ${{ github.ref_name=='main'}}
          echo $ {{ github.ref }}
          echo ${{ github.event_name }}

      - name: checkout branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name != 'develop' }}
        run: |          
          git pull
          git merge origin/${{ github.ref_name }}
          git push origin develop-merged

      # Insert steps for your pipeline
  
  test-api:
    name: test api
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        
      - name: Run API tests
        run: postman collection run "23289337-ae94e39e-d554-49ee-8b12-e7cfa39299ad" -e "23289337-72839b32-19c9-4b91-8903-21091d07336c"       
